language: java
jdk:
  - openjdk8

branches:
  only:
    - master
before_install:
  - chmod +x gradlew
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"



before_deploy:
  - zip -r springwithaws *
  - mkdir -p deploy
  - mv springwithaws.zip deploy/springwithaws.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: springwithaws-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # TRAVIS repo settings 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: springwithaws-build
    key: springwithaws.zip

    bundle_type: zip
    application: springwithaws
    deployment_group: springwithaws-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - cjfgh2449@gmail.com
