language: java
jdk:
    -openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - cjfgh2449@gmail.com
